### ISSUE TITLE
"Classes" in the Class description portlet is confusing

### ISSUE THREAD

**Issue by tudorache** [protegeproject/webprotege#371]
It is not clear what "Classes" mean on the class description portlet. It seems it should be "Superclasses". I suggest to remove it altogether.

![screenshot from 2016-11-02 13 53 25](https://cloud.githubusercontent.com/assets/2709502/19947135/fd20b482-a103-11e6-9958-928dee46f04d.png)

**Comment by csnyulas** [comment]
I think it is useful to have this section, especially for ontologies that have multiple superclasses (or to allow adding multiple superclasses), so I would suggest to keep it, but I would also suggest to rename it to "Superclasses" or something that is more intuitive than "Classes". Today I also got confused by the meaning of "Classes", that's why I looked up this issue to suggest we fixed it for version 3.0.

**Comment by csnyulas** [comment]
This was pointed out as confusing by multiple short course participants. Can we change the heading of the section?

**Comment by csnyulas** [comment]
Another idea would be to call it "Parent Classes".

**Comment by csnyulas** [comment]
Or how about labeling it "Is A".
This would help the user create sounder class hierarchies, but may confuse beginner users or non-native English speakers.
