### ISSUE TITLE
Build WebProtege 3.0 from Source (3.0.0-SNAPSHOT)?

### ISSUE THREAD

**Issue by lifan0127** [protegeproject/webprotege#409]
Dear Protege Team,

I was excited to find out WebProtege 3.0 under development and interested in trying out its new features. Since I cannot use the Stanford hosted version due to data confidentiality issue, I built a WAR file from the source code in GitHub and deployed to my Tomcat server. While the build appeared to be successful, the application is not usable.

```bash
[INFO] Building jar: /user/webprotege/target/webprotege-3.0.0-SNAPSHOT-lib.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 06:04 min
[INFO] Finished at: 2017-07-17T01:05:11+00:00
[INFO] Final Memory: 105M/669M
[INFO] ------------------------------------------------------------------------
```

1. There is no new user signup menu on the landing page. 

![image](https://user-images.githubusercontent.com/7218193/28266132-426bdcf6-6ac1-11e7-8bae-0f2db803113f.png)

2. On the project list page, both "Create Project" and "Upload Project" buttons are disabled. 

![image](https://user-images.githubusercontent.com/7218193/28265912-2807f558-6ac0-11e7-9fbb-016f0d3fb80b.png)

3. If I "enable" those buttons by modifying the HTML in ChromeDevTool, I would get a "Permission denied" error when creating a new project.

![image](https://user-images.githubusercontent.com/7218193/28265996-ad97fd08-6ac0-11e7-8309-8bcb6808e643.png)

My system: CentOS 7, Java 8, MongoDB 3.4.6, Tomcat 8.5.16

I understand the 3.0 version has not been released yet. I am just wondering if it is ready for public test. If so I would be very interested.

Thanks!!

**Comment by matthewhorridge** [comment]
Hi,

WebProtege 3 isn’t quite ready for download by third parties yet.  We’re still ironing a few things out and finalising what’s going to be in the release.

Cheers,

Matthew


On 17 Jul 2017, at 04:34, Fan Li <notifications@github.com<mailto:notifications@github.com>> wrote:


Dear Protege Team,

I was excited to find out WebProtege 3.0 under development and interested in trying out its new features. Since I cannot use the Stanford hosted version due to data confidentiality issue, I built a WAR file from the source code in GitHub and deployed to my Tomcat server. While the build appeared to be successful, the application is not usable.

[INFO] Building jar: /user/webprotege/target/webprotege-3.0.0-SNAPSHOT-lib.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 06:04 min
[INFO] Finished at: 2017-07-17T01:05:11+00:00
[INFO] Final Memory: 105M/669M
[INFO] ------------------------------------------------------------------------

  1.  There is no new user signup menu on the landing page.

[image]<https://user-images.githubusercontent.com/7218193/28266132-426bdcf6-6ac1-11e7-8bae-0f2db803113f.png>

  1.  On the project list page, both "Create Project" and "Upload Project" buttons are disabled.

[image]<https://user-images.githubusercontent.com/7218193/28265912-2807f558-6ac0-11e7-9fbb-016f0d3fb80b.png>

  1.  If I "enable" those buttons by modifying the HTML in ChromeDevTool, I would get a "Permission denied" error when creating a new project.

[image]<https://user-images.githubusercontent.com/7218193/28265996-ad97fd08-6ac0-11e7-8309-8bcb6808e643.png>

My system: CentOS 7, Java 8, MongoDB 3.4.6, Tomcat 8.5.16

I understand the 3.0 version has not been released yet. I am just wondering if it is ready for public test. If so I would be very interested.

Thanks!!

**Comment by lifan0127** [comment]
@matthewhorridge Thanks for letting me know! I look forward to its release in the near future.

**Comment by jindrichmynarz** [comment]
The described state is still the case for the [3.0.0 release](https://github.com/protegeproject/webprotege/releases/tag/v3.0.0). How to enable the "Create project" button?

**Comment by matthewhorridge** [comment]
@jindrichmynarz you need to log in with an admin account and then visit #/application/settings to enable project creation amongst other things.  You can find details on how to set things up here:

https://github.com/protegeproject/webprotege/wiki/WebProtégé-3.0.0-Installation

**Comment by jindrichmynarz** [comment]
Thanks! I overlooked the other tabs in the application settings.
