### ISSUE TITLE
Enable the configuration of the email server from admin tool  

### ISSUE THREAD

**Issue by csnyulas** [protegeproject/webprotege#438]
Would be nice to have a separate section in the "admin tool" where one can configure the email server used for notifications regarding watched entities and to reset user passwords.

**Comment by matthewhorridge** [comment]
@tudorache and I chatted about this some time ago.  In the end the decision to keep this config info as a properties file was taken because there are [many (interdependent) config properties](https://javaee.github.io/javamail/docs/api/com/sun/mail/smtp/package-summary.html#package.description) and different systems will require different (possibly complex) combinations.  Also, the properties, as they are, should be understandable by any system admin, are fairly well documented, and are somewhat straightforward to configure in a properties file.  Hard to design a good robust UI for this really.
