### ISSUE TITLE
Email notifications should not be sent to the user that caused the email notification to be generated

### ISSUE THREAD

**Issue by matthewhorridge** [protegeproject/webprotege#459]
If a user posts a comment in a thread then they don't need to receive an email notification to tell them that they've done this.

**Comment by csnyulas** [comment]
I think this should be a configuration option. Sometimes it is useful to get emails about your own contribution as well. Especially if these notifications are made to create and email thread. If you have all notifications, you can see in your email client the full conversation. Otherwise often it is hard to know the context.

**Comment by matthewhorridge** [comment]
> I think this should be a configuration option.

Probably should, but I'll turn this off for now.  We'll have a new issue for the config option.
